### ISSUE TITLE
Getting 'negative WaitGroup counter' when Track.Wait

### ISSUE THREAD

**Issue by fabiofalci** [op/go-libspotify#11]
Sometimes when waiting for a track `track.Wait()` I get this panic:

	...
	playlistcontainer loaded
	playlist container loaded
	panic: sync: negative WaitGroup counter

	goroutine 7 [running, locked to thread]:
	sync.(*WaitGroup).Add(0xc2080384c0, 0xffffffffffffffff)
		/usr/lib/go/src/sync/waitgroup.go:67 +0x96
	sync.(*WaitGroup).Done(0xc2080384c0)
		/usr/lib/go/src/sync/waitgroup.go:85 +0x31
	github.com/op/go-libspotify/spotify.(*Track).cbUpdated(0xc2080384b0)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:1788 +0x4c
	github.com/op/go-libspotify/spotify.(*Session).sendUpdates(0xc208092000, 0xc208092098, 0xc208038570)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:959 +0xb6
	github.com/op/go-libspotify/spotify.(*Session).cbMetadataUpdated(0xc208092000)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:980 +0x4a
	github.com/op/go-libspotify/spotify.sessionCall(0x7feea4079b70, 0x636848)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:185 +0x3b
	github.com/op/go-libspotify/spotify.go_metadata_updated(0x7feea4079b70)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:1115 +0x34
	github.com/op/go-libspotify/spotify._Cfunc_sp_session_process_events(0x7feea4079b70, 0xc208055e30, 0x0)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/:905 +0x43
	github.com/op/go-libspotify/spotify.(*Session).processEvents(0xc208092000)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:878 +0xd6
	github.com/op/go-libspotify/spotify.func·001()
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:243 +0x141
	created by github.com/op/go-libspotify/spotify.NewSession
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:244 +0x819

	goroutine 6 [runnable]:
	sync.(*WaitGroup).Wait(0xc2080384c0)
		/usr/lib/go/src/sync/waitgroup.go:132 +0x169
	github.com/op/go-libspotify/spotify.(*Track).Wait(0xc2080384b0)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:1793 +0x38
	github.com/fabiofalci/sconsify/sconsify.ToSconsifyTrack(0xc2080384b0, 0xc2080384b0)
		/home/fabio/go/src/github.com/fabiofalci/sconsify/sconsify/track.go:26 +0x33
	github.com/fabiofalci/sconsify/spotify.(*Spotify).initPlaylist(0xc2080107e0)
		/home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:172 +0x208
	github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation(0xc2080107e0)
		/home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:135 +0x28
	github.com/fabiofalci/sconsify/spotify.(*Spotify).checkIfLoggedIn(0xc2080107e0, 0x0, 0x0)
		/home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:109 +0x122
	github.com/fabiofalci/sconsify/spotify.initialiseSpotify(0xc20802a2ca, 0xa, 0xc20800a8f8, 0x8, 0x8, 0xc20801e7e0, 0xc20800a860, 0x0, 0x0)
		/home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:47 +0x1ea
	github.com/fabiofalci/sconsify/spotify.Initialise(0xc20802a2ca, 0xa, 0xc20800a8f8, 0x8, 0x8, 0xc20801e7e0, 0xc20800a860)
		/home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:26 +0x81
	created by main.main
		/home/fabio/go/src/github.com/fabiofalci/sconsify/sconsify.go:36 +0x26a

After some debugging I can see the follow behavior when things go right when loading one Track at the time:

* Track is being loaded by `newTrack`
* My code calls `track.Wait()` and gets blocked
* `cbUpdated` will be called when `cbMetadataUpdated` gets updates. If track is loaded then `WaitGroup.Done()` , else do nothing (waiting for more update)
* When `WaitGroup.Done()` then `track.Wait()` will get unblocked

And when I get the panic:

* Track is being loaded by `newTrack`
* My code calls `track.Wait()` and gets blocked
* `cbUpdated` is called then `WaitGroup.Done()`
* `cbUpdated` is called then `WaitGroup.Done()`. Here it panics.

The problem is that `cbUpdated` is called twice and in both the track is already loaded so it calls `WaitGroup` to unblock `Wait` but `WaitGroup.Add(1)` is called only once by `newTrack` so only one call is expected. 

I'll try to understand more about this issue but if I'm missing something please let me know.

Thanks

**Comment by op** [comment]
I haven't seen that one myself but it definitely smells like a bug somewhere. I don't think I'll be able to spend much time on it right now.

**Comment by fabiofalci** [comment]
Hi Örjan,

Let me take a step back.
Do you think this a correct algorithm to load all playlists/tracks?
https://github.com/fabiofalci/go-libspotify/commit/7cde1d3b49f1c230be952178c7eb2e074bb0dee6

It throws an error most of the time (attached at the end) and very occasionally the `panic: sync: negative WaitGroup counter` problem.

Because I need to load all playlist/tracks to show to the user on my system there is a similar algorithm which works most of the time, it doesn't throw the same attached error but sometimes I get the `panic: sync: negative WaitGroup counter` problem too:
https://github.com/fabiofalci/sconsify/blob/master/spotify/spotify_playlists.go#L10

Thanks

        fatal error: unexpected signal during runtime execution
	[signal 0xb code=0x1 addr=0x0 pc=0x7ff70b5d2a68]

	runtime stack:
	runtime.gothrow(0x5d5eb0, 0x2a)
		/usr/lib/go/src/runtime/panic.go:503 +0x8e
	runtime.sigpanic()
		/usr/lib/go/src/runtime/sigpanic_unix.go:14 +0x5e

	goroutine 7 [syscall, locked to thread]:
	runtime.cgocall_errno(0x40b800, 0xc208019df8, 0x0)
		/usr/lib/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc208019dd8 sp=0xc208019db0
	github.com/op/go-libspotify/spotify._Cfunc_sp_session_process_events(0x153cec0, 0xc208019e30, 0x0)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/:905 +0x43 fp=0xc208019df8 sp=0xc208019dd8
	github.com/op/go-libspotify/spotify.(*Session).processEvents(0xc208078180)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:878 +0xd6 fp=0xc208019f50 sp=0xc208019df8
	github.com/op/go-libspotify/spotify.func·001()
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:243 +0x141 fp=0xc208019fe0 sp=0xc208019f50
	runtime.goexit()
		/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208019fe8 sp=0xc208019fe0
	created by github.com/op/go-libspotify/spotify.NewSession
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:244 +0x819

	goroutine 1 [syscall, locked to thread]:
	github.com/op/go-libspotify/spotify._Cfunc_sp_session_playlistcontainer(0x153cec0, 0x0)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/:887 +0x44
	github.com/op/go-libspotify/spotify.newPlaylistContainer(0xc208078180, 0x0, 0x0, 0x0)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:1337 +0x196
	github.com/op/go-libspotify/spotify.(*Session).Playlists(0xc208078180, 0x1, 0x0, 0x0)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:532 +0x3a
	main.main()
		/home/fabio/go/src/github.com/op/go-libspotify/examples/portaudio/portaudio.go:320 +0xb4f

	goroutine 5 [syscall]:
	os/signal.loop()
		/usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
	created by os/signal.init·1
		/usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

	goroutine 17 [syscall, locked to thread]:
	runtime.goexit()
		/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

	goroutine 6 [select]:
	main.(*audioWriter).streamWriter(0xc20803a540, 0xc20801e300)
		/home/fabio/go/src/github.com/op/go-libspotify/examples/portaudio/portaudio.go:114 +0x3fc
	created by main.newAudioWriter
		/home/fabio/go/src/github.com/op/go-libspotify/examples/portaudio/portaudio.go:78 +0x174

	goroutine 9 [select]:
	github.com/op/go-libspotify/spotify.(*Session).processBackground(0xc208078180)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:900 +0x2ad
	created by github.com/op/go-libspotify/spotify.NewSession
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:250 +0x8c8

	goroutine 10 [chan receive]:
	main.func·001()
		/home/fabio/go/src/github.com/op/go-libspotify/examples/portaudio/portaudio.go:302 +0x5a
	created by main.main
		/home/fabio/go/src/github.com/op/go-libspotify/examples/portaudio/portaudio.go:305 +0x8cc

	goroutine 18 [syscall, locked to thread]:
	runtime.goexit()
		/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

**Comment by op** [comment]
Sorry, I've been so busy lately and have not had the time to look at this.

Without diving into the code, maybe the wg.Done() calls can be wrapped with a sync.Once to make sure they are only decreased once? If that'd solve the problem, I'd be more than happy to merge it.

I also wish there would be an easy way to write tests for these kinds of things. That'd be an awesome future thing to do as well.

**Comment by fabiofalci** [comment]
Yeah, I've been using this version with `Once` and it's working fine: https://github.com/fabiofalci/go-libspotify/commit/2100480162e760b8d6193e4296e33f045566c6f0

Alright I'll try to organise a pull request in the next few days.

Thanks
